2023-09-21 20:04:32,641 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-09-21 20:04:39,905 [WARNING] django.request: Not Found: /
2023-09-21 20:04:46,957 [INFO] shopapp.views: Rendering shop index
2023-09-21 21:36:29,192 [INFO] django.utils.autoreload: /home/verghil/Desktop/python_django/somesite/shopapp/views.py changed, reloading.
2023-09-21 21:36:32,057 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-09-21 21:37:56,074 [INFO] django.utils.autoreload: /home/verghil/Desktop/python_django/somesite/shopapp/views.py changed, reloading.
2023-09-21 21:37:59,245 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-09-21 21:38:28,298 [INFO] django.utils.autoreload: /home/verghil/Desktop/python_django/somesite/shopapp/views.py changed, reloading.
2023-09-21 21:38:30,652 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-09-21 21:49:03,140 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-09-21 21:49:07,692 [WARNING] django.request: Not Found: /
2023-09-21 21:49:13,631 [INFO] shopapp.views: Rendering shop index
2023-09-21 21:49:20,605 [INFO] django.utils.autoreload: /home/verghil/Desktop/python_django/somesite/somesite/settings.py changed, reloading.
2023-09-21 21:49:30,516 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-09-21 21:49:43,488 [ERROR] django.request: Internal Server Error: /ru/shop/orders/export/
Traceback (most recent call last):
  File "/home/verghil/.local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/verghil/.local/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/verghil/.local/lib/python3.10/site-packages/sentry_sdk/integrations/django/views.py", line 84, in sentry_wrapped_callback
    return callback(request, *args, **kwargs)
  File "/home/verghil/.local/lib/python3.10/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/verghil/.local/lib/python3.10/site-packages/django/views/generic/base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/verghil/Desktop/python_django/somesite/shopapp/views.py", line 253, in get
    name = elem['uss']
KeyError: 'uss'
2023-09-21 21:51:19,932 [INFO] django.utils.autoreload: /home/verghil/Desktop/python_django/somesite/shopapp/views.py changed, reloading.
2023-09-21 21:51:29,925 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-09-24 20:01:11,908 [INFO] django.utils.autoreload: /home/verghil/Desktop/python_django/somesite/shopapp/views.py changed, reloading.
2023-09-24 20:01:19,139 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-09-26 20:48:21,281 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-10-08 18:11:49,097 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-10-08 18:11:52,953 [WARNING] django.request: Not Found: /
2023-10-08 18:16:18,991 [INFO] django.utils.autoreload: /home/verghil/Desktop/python_django/somesite/shopapp/admin.py changed, reloading.
2023-10-08 18:16:30,093 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-10-08 18:16:56,818 [ERROR] django.request: Internal Server Error: /ru/admin/shopapp/product/
Traceback (most recent call last):
  File "/home/verghil/.local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/verghil/.local/lib/python3.10/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
  File "/home/verghil/.local/lib/python3.10/site-packages/sentry_sdk/integrations/django/views.py", line 38, in sentry_patched_render
    return old_render(self)
  File "/home/verghil/.local/lib/python3.10/site-packages/django/template/response.py", line 114, in render
    self.content = self.rendered_content
  File "/home/verghil/.local/lib/python3.10/site-packages/sentry_sdk/integrations/django/templates.py", line 75, in rendered_content
    return real_rendered_content.fget(self)
  File "/home/verghil/.local/lib/python3.10/site-packages/django/template/response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
  File "/home/verghil/.local/lib/python3.10/site-packages/django/template/response.py", line 74, in resolve_template
    return get_template(template, using=self.using)
  File "/home/verghil/.local/lib/python3.10/site-packages/django/template/loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: shopapp/products_changelist.html
2023-10-08 18:17:30,443 [ERROR] django.request: Internal Server Error: /ru/admin/shopapp/product/
Traceback (most recent call last):
  File "/home/verghil/.local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/verghil/.local/lib/python3.10/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
  File "/home/verghil/.local/lib/python3.10/site-packages/sentry_sdk/integrations/django/views.py", line 38, in sentry_patched_render
    return old_render(self)
  File "/home/verghil/.local/lib/python3.10/site-packages/django/template/response.py", line 114, in render
    self.content = self.rendered_content
  File "/home/verghil/.local/lib/python3.10/site-packages/sentry_sdk/integrations/django/templates.py", line 75, in rendered_content
    return real_rendered_content.fget(self)
  File "/home/verghil/.local/lib/python3.10/site-packages/django/template/response.py", line 92, in rendered_content
    return template.render(context, self._request)
  File "/home/verghil/.local/lib/python3.10/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/home/verghil/.local/lib/python3.10/site-packages/django/template/base.py", line 175, in render
    return self._render(context)
  File "/home/verghil/.local/lib/python3.10/site-packages/django/test/utils.py", line 112, in instrumented_test_render
    return self.nodelist.render(context)
  File "/home/verghil/.local/lib/python3.10/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/verghil/.local/lib/python3.10/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/verghil/.local/lib/python3.10/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/verghil/.local/lib/python3.10/site-packages/django/template/loader_tags.py", line 157, in render
    return compiled_parent._render(context)
  File "/home/verghil/.local/lib/python3.10/site-packages/django/test/utils.py", line 112, in instrumented_test_render
    return self.nodelist.render(context)
  File "/home/verghil/.local/lib/python3.10/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/verghil/.local/lib/python3.10/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/verghil/.local/lib/python3.10/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/verghil/.local/lib/python3.10/site-packages/django/template/loader_tags.py", line 157, in render
    return compiled_parent._render(context)
  File "/home/verghil/.local/lib/python3.10/site-packages/django/test/utils.py", line 112, in instrumented_test_render
    return self.nodelist.render(context)
  File "/home/verghil/.local/lib/python3.10/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/verghil/.local/lib/python3.10/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/verghil/.local/lib/python3.10/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/verghil/.local/lib/python3.10/site-packages/django/template/loader_tags.py", line 157, in render
    return compiled_parent._render(context)
  File "/home/verghil/.local/lib/python3.10/site-packages/django/test/utils.py", line 112, in instrumented_test_render
    return self.nodelist.render(context)
  File "/home/verghil/.local/lib/python3.10/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/verghil/.local/lib/python3.10/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/verghil/.local/lib/python3.10/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/verghil/.local/lib/python3.10/site-packages/django/template/loader_tags.py", line 63, in render
    result = block.nodelist.render(context)
  File "/home/verghil/.local/lib/python3.10/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/verghil/.local/lib/python3.10/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/verghil/.local/lib/python3.10/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/verghil/.local/lib/python3.10/site-packages/django/template/loader_tags.py", line 63, in render
    result = block.nodelist.render(context)
  File "/home/verghil/.local/lib/python3.10/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/verghil/.local/lib/python3.10/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/verghil/.local/lib/python3.10/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/verghil/.local/lib/python3.10/site-packages/django/template/loader_tags.py", line 63, in render
    result = block.nodelist.render(context)
  File "/home/verghil/.local/lib/python3.10/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/verghil/.local/lib/python3.10/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/verghil/.local/lib/python3.10/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/verghil/.local/lib/python3.10/site-packages/django/template/defaulttags.py", line 471, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "/home/verghil/.local/lib/python3.10/site-packages/django/urls/base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "/home/verghil/.local/lib/python3.10/site-packages/django/urls/resolvers.py", line 828, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'import_product_csv' not found. 'import_product_csv' is not a valid view function or pattern name.
2023-10-08 18:17:57,243 [INFO] django.utils.autoreload: /home/verghil/Desktop/python_django/somesite/shopapp/admin.py changed, reloading.
2023-10-08 18:18:03,680 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-10-08 18:18:10,597 [ERROR] django.request: Internal Server Error: /ru/admin/shopapp/product/
Traceback (most recent call last):
  File "/home/verghil/.local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/verghil/.local/lib/python3.10/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
  File "/home/verghil/.local/lib/python3.10/site-packages/sentry_sdk/integrations/django/views.py", line 38, in sentry_patched_render
    return old_render(self)
  File "/home/verghil/.local/lib/python3.10/site-packages/django/template/response.py", line 114, in render
    self.content = self.rendered_content
  File "/home/verghil/.local/lib/python3.10/site-packages/sentry_sdk/integrations/django/templates.py", line 75, in rendered_content
    return real_rendered_content.fget(self)
  File "/home/verghil/.local/lib/python3.10/site-packages/django/template/response.py", line 92, in rendered_content
    return template.render(context, self._request)
  File "/home/verghil/.local/lib/python3.10/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/home/verghil/.local/lib/python3.10/site-packages/django/template/base.py", line 175, in render
    return self._render(context)
  File "/home/verghil/.local/lib/python3.10/site-packages/django/test/utils.py", line 112, in instrumented_test_render
    return self.nodelist.render(context)
  File "/home/verghil/.local/lib/python3.10/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/verghil/.local/lib/python3.10/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/verghil/.local/lib/python3.10/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/verghil/.local/lib/python3.10/site-packages/django/template/loader_tags.py", line 157, in render
    return compiled_parent._render(context)
  File "/home/verghil/.local/lib/python3.10/site-packages/django/test/utils.py", line 112, in instrumented_test_render
    return self.nodelist.render(context)
  File "/home/verghil/.local/lib/python3.10/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/verghil/.local/lib/python3.10/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/verghil/.local/lib/python3.10/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/verghil/.local/lib/python3.10/site-packages/django/template/loader_tags.py", line 157, in render
    return compiled_parent._render(context)
  File "/home/verghil/.local/lib/python3.10/site-packages/django/test/utils.py", line 112, in instrumented_test_render
    return self.nodelist.render(context)
  File "/home/verghil/.local/lib/python3.10/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/verghil/.local/lib/python3.10/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/verghil/.local/lib/python3.10/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/verghil/.local/lib/python3.10/site-packages/django/template/loader_tags.py", line 157, in render
    return compiled_parent._render(context)
  File "/home/verghil/.local/lib/python3.10/site-packages/django/test/utils.py", line 112, in instrumented_test_render
    return self.nodelist.render(context)
  File "/home/verghil/.local/lib/python3.10/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/verghil/.local/lib/python3.10/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/verghil/.local/lib/python3.10/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/verghil/.local/lib/python3.10/site-packages/django/template/loader_tags.py", line 63, in render
    result = block.nodelist.render(context)
  File "/home/verghil/.local/lib/python3.10/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/verghil/.local/lib/python3.10/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/verghil/.local/lib/python3.10/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/verghil/.local/lib/python3.10/site-packages/django/template/loader_tags.py", line 63, in render
    result = block.nodelist.render(context)
  File "/home/verghil/.local/lib/python3.10/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/verghil/.local/lib/python3.10/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/verghil/.local/lib/python3.10/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/verghil/.local/lib/python3.10/site-packages/django/template/loader_tags.py", line 63, in render
    result = block.nodelist.render(context)
  File "/home/verghil/.local/lib/python3.10/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/verghil/.local/lib/python3.10/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/verghil/.local/lib/python3.10/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/verghil/.local/lib/python3.10/site-packages/django/template/defaulttags.py", line 471, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "/home/verghil/.local/lib/python3.10/site-packages/django/urls/base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "/home/verghil/.local/lib/python3.10/site-packages/django/urls/resolvers.py", line 828, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'import_product_csv' not found. 'import_product_csv' is not a valid view function or pattern name.
2023-10-08 18:18:29,984 [INFO] django.utils.autoreload: /home/verghil/Desktop/python_django/somesite/shopapp/admin.py changed, reloading.
2023-10-08 18:18:37,429 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-10-08 18:19:05,273 [ERROR] django.request: Internal Server Error: /ru/admin/shopapp/product/import_product_csv/
Traceback (most recent call last):
  File "/home/verghil/.local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/verghil/.local/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/verghil/.local/lib/python3.10/site-packages/sentry_sdk/integrations/django/views.py", line 84, in sentry_wrapped_callback
    return callback(request, *args, **kwargs)
  File "/home/verghil/Desktop/python_django/somesite/shopapp/admin.py", line 41, in import_csv
    return render(request, 'admin/csv_from.html', context)
  File "/home/verghil/.local/lib/python3.10/site-packages/sentry_sdk/integrations/django/templates.py", line 102, in render
    return real_render(request, template_name, context, *args, **kwargs)
  File "/home/verghil/.local/lib/python3.10/site-packages/django/shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/verghil/.local/lib/python3.10/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "/home/verghil/.local/lib/python3.10/site-packages/django/template/loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: admin/csv_from.html
2023-10-08 18:19:50,502 [INFO] django.utils.autoreload: /home/verghil/Desktop/python_django/somesite/shopapp/admin.py changed, reloading.
2023-10-08 18:19:57,272 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-10-08 18:24:54,961 [INFO] django.utils.autoreload: /home/verghil/Desktop/python_django/somesite/shopapp/admin.py changed, reloading.
2023-10-08 18:25:08,350 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-10-08 18:26:59,391 [INFO] django.utils.autoreload: /home/verghil/Desktop/python_django/somesite/shopapp/admin.py changed, reloading.
2023-10-08 18:27:09,202 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-10-08 18:27:26,314 [INFO] django.utils.autoreload: /home/verghil/Desktop/python_django/somesite/shopapp/admin.py changed, reloading.
2023-10-08 18:27:40,540 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-10-08 18:28:10,588 [INFO] django.utils.autoreload: /home/verghil/Desktop/python_django/somesite/shopapp/admin.py changed, reloading.
2023-10-08 18:28:19,672 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-10-08 18:28:50,892 [INFO] django.utils.autoreload: /home/verghil/Desktop/python_django/somesite/shopapp/admin.py changed, reloading.
2023-10-08 18:29:00,342 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-10-08 18:29:14,598 [INFO] django.utils.autoreload: /home/verghil/Desktop/python_django/somesite/shopapp/admin.py changed, reloading.
2023-10-08 18:29:24,831 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-10-08 18:30:41,144 [INFO] django.utils.autoreload: /home/verghil/Desktop/python_django/somesite/shopapp/admin.py changed, reloading.
2023-10-08 18:30:54,639 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-10-08 18:31:48,213 [INFO] django.utils.autoreload: /home/verghil/Desktop/python_django/somesite/shopapp/admin.py changed, reloading.
2023-10-08 18:31:58,354 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-10-08 18:32:10,157 [INFO] django.utils.autoreload: /home/verghil/Desktop/python_django/somesite/shopapp/admin.py changed, reloading.
2023-10-08 18:32:18,506 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-10-08 18:32:37,321 [INFO] django.utils.autoreload: /home/verghil/Desktop/python_django/somesite/shopapp/admin.py changed, reloading.
2023-10-08 18:32:48,753 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-10-08 18:33:43,907 [ERROR] django.request: Internal Server Error: /ru/admin/shopapp/product/import_product_csv/
Traceback (most recent call last):
  File "/home/verghil/.local/lib/python3.10/site-packages/django/db/models/fields/__init__.py", line 1741, in to_python
    decimal_value = decimal.Decimal(value)
decimal.InvalidOperation: [<class 'decimal.ConversionSyntax'>]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/verghil/.local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/verghil/.local/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/verghil/.local/lib/python3.10/site-packages/sentry_sdk/integrations/django/views.py", line 84, in sentry_wrapped_callback
    return callback(request, *args, **kwargs)
  File "/home/verghil/Desktop/python_django/somesite/shopapp/admin.py", line 64, in import_csv
    Product.objects.bulk_create(products)
  File "/home/verghil/.local/lib/python3.10/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/verghil/.local/lib/python3.10/site-packages/django/db/models/query.py", line 803, in bulk_create
    returned_columns = self._batched_insert(
  File "/home/verghil/.local/lib/python3.10/site-packages/django/db/models/query.py", line 1831, in _batched_insert
    self._insert(
  File "/home/verghil/.local/lib/python3.10/site-packages/django/db/models/query.py", line 1805, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
  File "/home/verghil/.local/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 1821, in execute_sql
    for sql, params in self.as_sql():
  File "/home/verghil/.local/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 1745, in as_sql
    value_rows = [
  File "/home/verghil/.local/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 1746, in <listcomp>
    [
  File "/home/verghil/.local/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 1747, in <listcomp>
    self.prepare_value(field, self.pre_save_val(field, obj))
  File "/home/verghil/.local/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 1686, in prepare_value
    return field.get_db_prep_save(value, connection=self.connection)
  File "/home/verghil/.local/lib/python3.10/site-packages/django/db/models/fields/__init__.py", line 1760, in get_db_prep_save
    self.to_python(value), self.max_digits, self.decimal_places
  File "/home/verghil/.local/lib/python3.10/site-packages/django/db/models/fields/__init__.py", line 1743, in to_python
    raise exceptions.ValidationError(
django.core.exceptions.ValidationError: ['Значение “ "2299.00"” должно быть десятичным числом.']
2023-10-08 18:37:46,170 [INFO] django.utils.autoreload: /home/verghil/Desktop/python_django/somesite/shopapp/views.py changed, reloading.
2023-10-08 18:37:52,935 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-10-08 18:38:10,794 [INFO] django.utils.autoreload: /home/verghil/Desktop/python_django/somesite/shopapp/views.py changed, reloading.
2023-10-08 18:38:21,026 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-10-08 18:39:06,467 [INFO] django.utils.autoreload: /home/verghil/Desktop/python_django/somesite/shopapp/views.py changed, reloading.
2023-10-08 18:39:16,364 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-10-08 18:43:30,018 [INFO] django.utils.autoreload: /home/verghil/Desktop/python_django/somesite/shopapp/views.py changed, reloading.
2023-10-08 18:43:42,656 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-10-08 18:43:59,752 [INFO] django.utils.autoreload: /home/verghil/Desktop/python_django/somesite/shopapp/views.py changed, reloading.
2023-10-08 18:44:10,566 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-10-08 18:44:59,412 [INFO] django.utils.autoreload: /home/verghil/Desktop/python_django/somesite/shopapp/views.py changed, reloading.
2023-10-08 18:45:10,251 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-10-08 18:46:22,746 [INFO] django.utils.autoreload: /home/verghil/Desktop/python_django/somesite/shopapp/views.py changed, reloading.
2023-10-08 18:46:29,875 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-10-08 18:46:42,714 [INFO] django.utils.autoreload: /home/verghil/Desktop/python_django/somesite/shopapp/views.py changed, reloading.
2023-10-08 18:46:53,022 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-10-08 18:47:47,635 [INFO] django.utils.autoreload: /home/verghil/Desktop/python_django/somesite/shopapp/views.py changed, reloading.
2023-10-08 18:47:59,831 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-10-08 18:49:15,633 [INFO] django.utils.autoreload: /home/verghil/Desktop/python_django/somesite/shopapp/views.py changed, reloading.
2023-10-08 18:49:26,573 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-10-08 18:49:47,550 [INFO] django.utils.autoreload: /home/verghil/Desktop/python_django/somesite/shopapp/views.py changed, reloading.
2023-10-08 18:49:57,807 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-10-08 18:50:09,833 [WARNING] django.request: Not Found: /ru/api/
2023-10-08 18:50:18,752 [WARNING] django.request: Not Found: /ru/api/products
2023-10-08 18:50:27,684 [WARNING] django.request: Not Found: /ru/api/shop
2023-10-08 18:50:48,640 [INFO] shopapp.views: Rendering shop index
2023-10-08 18:54:05,526 [INFO] django.utils.autoreload: /home/verghil/Desktop/python_django/somesite/shopapp/views.py changed, reloading.
2023-10-08 18:54:11,827 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-10-08 18:54:41,435 [INFO] django.utils.autoreload: /home/verghil/Desktop/python_django/somesite/shopapp/views.py changed, reloading.
2023-10-08 18:54:49,319 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-10-08 18:55:59,893 [INFO] django.utils.autoreload: /home/verghil/Desktop/python_django/somesite/shopapp/admin.py changed, reloading.
2023-10-08 18:56:07,177 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-10-08 18:57:03,079 [INFO] django.utils.autoreload: /home/verghil/Desktop/python_django/somesite/shopapp/admin.py changed, reloading.
2023-10-08 18:57:13,635 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-10-08 18:58:08,025 [INFO] django.utils.autoreload: /home/verghil/Desktop/python_django/somesite/shopapp/admin.py changed, reloading.
2023-10-08 18:58:15,400 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-10-08 18:58:44,739 [INFO] django.utils.autoreload: /home/verghil/Desktop/python_django/somesite/shopapp/admin.py changed, reloading.
2023-10-08 18:58:54,722 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-10-08 18:59:02,548 [INFO] django.utils.autoreload: /home/verghil/Desktop/python_django/somesite/shopapp/admin.py changed, reloading.
2023-10-08 18:59:09,625 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-10-08 19:00:16,867 [INFO] django.utils.autoreload: /home/verghil/Desktop/python_django/somesite/shopapp/admin.py changed, reloading.
2023-10-08 19:00:24,272 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-10-08 19:01:15,979 [INFO] django.utils.autoreload: /home/verghil/Desktop/python_django/somesite/shopapp/admin.py changed, reloading.
2023-10-08 19:01:25,057 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-10-08 19:02:45,733 [INFO] django.utils.autoreload: /home/verghil/Desktop/python_django/somesite/shopapp/views.py changed, reloading.
2023-10-08 19:02:53,279 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-10-08 19:04:16,875 [INFO] django.utils.autoreload: /home/verghil/Desktop/python_django/somesite/shopapp/views.py changed, reloading.
2023-10-08 19:04:34,405 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-10-08 19:04:52,710 [INFO] django.utils.autoreload: /home/verghil/Desktop/python_django/somesite/shopapp/views.py changed, reloading.
2023-10-08 19:05:01,794 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-10-08 19:06:05,304 [INFO] django.utils.autoreload: /home/verghil/Desktop/python_django/somesite/shopapp/views.py changed, reloading.
2023-10-08 19:06:12,462 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-10-08 19:06:52,616 [INFO] django.utils.autoreload: /home/verghil/Desktop/python_django/somesite/shopapp/views.py changed, reloading.
2023-10-08 19:07:02,109 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-10-08 19:07:33,250 [INFO] django.utils.autoreload: /home/verghil/Desktop/python_django/somesite/shopapp/views.py changed, reloading.
2023-10-08 19:07:40,261 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-10-08 19:09:39,765 [INFO] django.utils.autoreload: /home/verghil/Desktop/python_django/somesite/shopapp/views.py changed, reloading.
2023-10-08 19:09:49,104 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-10-08 19:10:03,335 [INFO] django.utils.autoreload: /home/verghil/Desktop/python_django/somesite/shopapp/views.py changed, reloading.
2023-10-08 19:10:13,207 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-10-08 19:10:22,802 [WARNING] django.request: Method Not Allowed: /ru/shop/api/products/upload_csv/
2023-10-08 19:20:01,555 [INFO] django.utils.autoreload: /home/verghil/Desktop/python_django/somesite/BlogApp/models.py changed, reloading.
2023-10-08 19:20:08,888 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-10-08 19:23:04,431 [INFO] django.utils.autoreload: /home/verghil/Desktop/python_django/somesite/BlogApp/views.py changed, reloading.
2023-10-08 19:23:10,855 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-10-08 19:26:49,134 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-10-08 19:26:56,511 [WARNING] django.request: Not Found: /ru/
2023-10-08 19:27:05,241 [WARNING] django.request: Not Found: /ru/article/
2023-10-08 19:27:32,329 [WARNING] django.request: Not Found: /ru/articles/
2023-10-08 19:27:50,297 [INFO] django.utils.autoreload: /home/verghil/Desktop/python_django/somesite/BlogApp/urls.py changed, reloading.
2023-10-08 19:27:56,444 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-10-08 19:31:42,634 [WARNING] django.request: Not Found: /ru/articles/
2023-10-08 19:32:05,015 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-10-08 19:32:09,307 [WARNING] django.request: Not Found: /
2023-10-08 19:32:13,766 [WARNING] django.request: Not Found: /ru/
2023-10-08 19:32:18,050 [WARNING] django.request: Not Found: /ru/article/
2023-10-08 19:32:20,946 [WARNING] django.request: Not Found: /ru/articles/
2023-10-08 19:32:24,297 [WARNING] django.request: Not Found: /ru/article/
2023-10-08 19:32:43,914 [ERROR] django.request: Internal Server Error: /ru/article/articles/
Traceback (most recent call last):
  File "/home/verghil/.local/lib/python3.10/site-packages/django/template/base.py", line 505, in parse
    compile_func = self.tags[command]
KeyError: 'endfor'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/verghil/.local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/verghil/.local/lib/python3.10/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
  File "/home/verghil/.local/lib/python3.10/site-packages/sentry_sdk/integrations/django/views.py", line 38, in sentry_patched_render
    return old_render(self)
  File "/home/verghil/.local/lib/python3.10/site-packages/django/template/response.py", line 114, in render
    self.content = self.rendered_content
  File "/home/verghil/.local/lib/python3.10/site-packages/sentry_sdk/integrations/django/templates.py", line 75, in rendered_content
    return real_rendered_content.fget(self)
  File "/home/verghil/.local/lib/python3.10/site-packages/django/template/response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
  File "/home/verghil/.local/lib/python3.10/site-packages/django/template/response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
  File "/home/verghil/.local/lib/python3.10/site-packages/django/template/loader.py", line 42, in select_template
    return engine.get_template(template_name)
  File "/home/verghil/.local/lib/python3.10/site-packages/django/template/backends/django.py", line 33, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "/home/verghil/.local/lib/python3.10/site-packages/django/template/engine.py", line 175, in get_template
    template, origin = self.find_template(template_name)
  File "/home/verghil/.local/lib/python3.10/site-packages/django/template/engine.py", line 157, in find_template
    template = loader.get_template(name, skip=skip)
  File "/home/verghil/.local/lib/python3.10/site-packages/django/template/loaders/cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
  File "/home/verghil/.local/lib/python3.10/site-packages/django/template/loaders/base.py", line 28, in get_template
    return Template(
  File "/home/verghil/.local/lib/python3.10/site-packages/django/template/base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
  File "/home/verghil/.local/lib/python3.10/site-packages/django/template/base.py", line 200, in compile_nodelist
    return parser.parse()
  File "/home/verghil/.local/lib/python3.10/site-packages/django/template/base.py", line 513, in parse
    raise self.error(token, e)
  File "/home/verghil/.local/lib/python3.10/site-packages/django/template/base.py", line 511, in parse
    compiled_result = compile_func(self, token)
  File "/home/verghil/.local/lib/python3.10/site-packages/django/template/loader_tags.py", line 293, in do_extends
    nodelist = parser.parse()
  File "/home/verghil/.local/lib/python3.10/site-packages/django/template/base.py", line 513, in parse
    raise self.error(token, e)
  File "/home/verghil/.local/lib/python3.10/site-packages/django/template/base.py", line 511, in parse
    compiled_result = compile_func(self, token)
  File "/home/verghil/.local/lib/python3.10/site-packages/django/template/loader_tags.py", line 232, in do_block
    nodelist = parser.parse(("endblock",))
  File "/home/verghil/.local/lib/python3.10/site-packages/django/template/base.py", line 513, in parse
    raise self.error(token, e)
  File "/home/verghil/.local/lib/python3.10/site-packages/django/template/base.py", line 511, in parse
    compiled_result = compile_func(self, token)
  File "/home/verghil/.local/lib/python3.10/site-packages/django/template/defaulttags.py", line 953, in do_if
    nodelist = parser.parse(("elif", "else", "endif"))
  File "/home/verghil/.local/lib/python3.10/site-packages/django/template/base.py", line 507, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "/home/verghil/.local/lib/python3.10/site-packages/django/template/base.py", line 558, in invalid_block_tag
    raise self.error(
django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 25: 'endfor', expected 'elif', 'else' or 'endif'. Did you forget to register or load this tag?
2023-10-08 19:33:09,640 [INFO] django.utils.autoreload: /home/verghil/Desktop/python_django/somesite/BlogApp/urls.py changed, reloading.
2023-10-08 19:33:16,284 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-10-08 19:33:21,741 [ERROR] django.request: Internal Server Error: /ru/article/
Traceback (most recent call last):
  File "/home/verghil/.local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/verghil/.local/lib/python3.10/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
  File "/home/verghil/.local/lib/python3.10/site-packages/sentry_sdk/integrations/django/views.py", line 38, in sentry_patched_render
    return old_render(self)
  File "/home/verghil/.local/lib/python3.10/site-packages/django/template/response.py", line 114, in render
    self.content = self.rendered_content
  File "/home/verghil/.local/lib/python3.10/site-packages/sentry_sdk/integrations/django/templates.py", line 75, in rendered_content
    return real_rendered_content.fget(self)
  File "/home/verghil/.local/lib/python3.10/site-packages/django/template/response.py", line 92, in rendered_content
    return template.render(context, self._request)
  File "/home/verghil/.local/lib/python3.10/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/home/verghil/.local/lib/python3.10/site-packages/django/template/base.py", line 175, in render
    return self._render(context)
  File "/home/verghil/.local/lib/python3.10/site-packages/django/test/utils.py", line 112, in instrumented_test_render
    return self.nodelist.render(context)
  File "/home/verghil/.local/lib/python3.10/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/verghil/.local/lib/python3.10/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/verghil/.local/lib/python3.10/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/verghil/.local/lib/python3.10/site-packages/django/template/loader_tags.py", line 157, in render
    return compiled_parent._render(context)
  File "/home/verghil/.local/lib/python3.10/site-packages/django/test/utils.py", line 112, in instrumented_test_render
    return self.nodelist.render(context)
  File "/home/verghil/.local/lib/python3.10/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/verghil/.local/lib/python3.10/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/verghil/.local/lib/python3.10/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/verghil/.local/lib/python3.10/site-packages/django/template/loader_tags.py", line 63, in render
    result = block.nodelist.render(context)
  File "/home/verghil/.local/lib/python3.10/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/verghil/.local/lib/python3.10/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/verghil/.local/lib/python3.10/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/verghil/.local/lib/python3.10/site-packages/django/template/defaulttags.py", line 321, in render
    return nodelist.render(context)
  File "/home/verghil/.local/lib/python3.10/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/verghil/.local/lib/python3.10/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/verghil/.local/lib/python3.10/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/verghil/.local/lib/python3.10/site-packages/django/template/defaulttags.py", line 238, in render
    nodelist.append(node.render_annotated(context))
  File "/home/verghil/.local/lib/python3.10/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/verghil/.local/lib/python3.10/site-packages/django/template/defaulttags.py", line 471, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "/home/verghil/.local/lib/python3.10/site-packages/django/urls/base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "/home/verghil/.local/lib/python3.10/site-packages/django/urls/resolvers.py", line 828, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'article' not found. 'article' is not a valid view function or pattern name.
2023-10-08 19:34:02,023 [ERROR] django.request: Internal Server Error: /ru/article/
Traceback (most recent call last):
  File "/home/verghil/.local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/verghil/.local/lib/python3.10/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
  File "/home/verghil/.local/lib/python3.10/site-packages/sentry_sdk/integrations/django/views.py", line 38, in sentry_patched_render
    return old_render(self)
  File "/home/verghil/.local/lib/python3.10/site-packages/django/template/response.py", line 114, in render
    self.content = self.rendered_content
  File "/home/verghil/.local/lib/python3.10/site-packages/sentry_sdk/integrations/django/templates.py", line 75, in rendered_content
    return real_rendered_content.fget(self)
  File "/home/verghil/.local/lib/python3.10/site-packages/django/template/response.py", line 92, in rendered_content
    return template.render(context, self._request)
  File "/home/verghil/.local/lib/python3.10/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/home/verghil/.local/lib/python3.10/site-packages/django/template/base.py", line 175, in render
    return self._render(context)
  File "/home/verghil/.local/lib/python3.10/site-packages/django/test/utils.py", line 112, in instrumented_test_render
    return self.nodelist.render(context)
  File "/home/verghil/.local/lib/python3.10/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/verghil/.local/lib/python3.10/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/verghil/.local/lib/python3.10/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/verghil/.local/lib/python3.10/site-packages/django/template/loader_tags.py", line 157, in render
    return compiled_parent._render(context)
  File "/home/verghil/.local/lib/python3.10/site-packages/django/test/utils.py", line 112, in instrumented_test_render
    return self.nodelist.render(context)
  File "/home/verghil/.local/lib/python3.10/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/verghil/.local/lib/python3.10/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/verghil/.local/lib/python3.10/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/verghil/.local/lib/python3.10/site-packages/django/template/loader_tags.py", line 63, in render
    result = block.nodelist.render(context)
  File "/home/verghil/.local/lib/python3.10/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/verghil/.local/lib/python3.10/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/verghil/.local/lib/python3.10/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/verghil/.local/lib/python3.10/site-packages/django/template/defaulttags.py", line 321, in render
    return nodelist.render(context)
  File "/home/verghil/.local/lib/python3.10/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/verghil/.local/lib/python3.10/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/verghil/.local/lib/python3.10/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/verghil/.local/lib/python3.10/site-packages/django/template/defaulttags.py", line 238, in render
    nodelist.append(node.render_annotated(context))
  File "/home/verghil/.local/lib/python3.10/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/verghil/.local/lib/python3.10/site-packages/django/template/defaulttags.py", line 471, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "/home/verghil/.local/lib/python3.10/site-packages/django/urls/base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "/home/verghil/.local/lib/python3.10/site-packages/django/urls/resolvers.py", line 828, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'blogapp' not found. 'blogapp' is not a valid view function or pattern name.
2023-10-08 19:34:06,944 [ERROR] django.request: Internal Server Error: /ru/article/
Traceback (most recent call last):
  File "/home/verghil/.local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/verghil/.local/lib/python3.10/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
  File "/home/verghil/.local/lib/python3.10/site-packages/sentry_sdk/integrations/django/views.py", line 38, in sentry_patched_render
    return old_render(self)
  File "/home/verghil/.local/lib/python3.10/site-packages/django/template/response.py", line 114, in render
    self.content = self.rendered_content
  File "/home/verghil/.local/lib/python3.10/site-packages/sentry_sdk/integrations/django/templates.py", line 75, in rendered_content
    return real_rendered_content.fget(self)
  File "/home/verghil/.local/lib/python3.10/site-packages/django/template/response.py", line 92, in rendered_content
    return template.render(context, self._request)
  File "/home/verghil/.local/lib/python3.10/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/home/verghil/.local/lib/python3.10/site-packages/django/template/base.py", line 175, in render
    return self._render(context)
  File "/home/verghil/.local/lib/python3.10/site-packages/django/test/utils.py", line 112, in instrumented_test_render
    return self.nodelist.render(context)
  File "/home/verghil/.local/lib/python3.10/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/verghil/.local/lib/python3.10/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/verghil/.local/lib/python3.10/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/verghil/.local/lib/python3.10/site-packages/django/template/loader_tags.py", line 157, in render
    return compiled_parent._render(context)
  File "/home/verghil/.local/lib/python3.10/site-packages/django/test/utils.py", line 112, in instrumented_test_render
    return self.nodelist.render(context)
  File "/home/verghil/.local/lib/python3.10/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/verghil/.local/lib/python3.10/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/verghil/.local/lib/python3.10/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/verghil/.local/lib/python3.10/site-packages/django/template/loader_tags.py", line 63, in render
    result = block.nodelist.render(context)
  File "/home/verghil/.local/lib/python3.10/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/verghil/.local/lib/python3.10/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/verghil/.local/lib/python3.10/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/verghil/.local/lib/python3.10/site-packages/django/template/defaulttags.py", line 321, in render
    return nodelist.render(context)
  File "/home/verghil/.local/lib/python3.10/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/verghil/.local/lib/python3.10/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/verghil/.local/lib/python3.10/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/verghil/.local/lib/python3.10/site-packages/django/template/defaulttags.py", line 238, in render
    nodelist.append(node.render_annotated(context))
  File "/home/verghil/.local/lib/python3.10/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/verghil/.local/lib/python3.10/site-packages/django/template/defaulttags.py", line 471, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "/home/verghil/.local/lib/python3.10/site-packages/django/urls/base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "/home/verghil/.local/lib/python3.10/site-packages/django/urls/resolvers.py", line 828, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'blogapp' not found. 'blogapp' is not a valid view function or pattern name.
2023-10-08 19:34:13,089 [ERROR] django.request: Internal Server Error: /ru/article/
Traceback (most recent call last):
  File "/home/verghil/.local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/verghil/.local/lib/python3.10/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
  File "/home/verghil/.local/lib/python3.10/site-packages/sentry_sdk/integrations/django/views.py", line 38, in sentry_patched_render
    return old_render(self)
  File "/home/verghil/.local/lib/python3.10/site-packages/django/template/response.py", line 114, in render
    self.content = self.rendered_content
  File "/home/verghil/.local/lib/python3.10/site-packages/sentry_sdk/integrations/django/templates.py", line 75, in rendered_content
    return real_rendered_content.fget(self)
  File "/home/verghil/.local/lib/python3.10/site-packages/django/template/response.py", line 92, in rendered_content
    return template.render(context, self._request)
  File "/home/verghil/.local/lib/python3.10/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/home/verghil/.local/lib/python3.10/site-packages/django/template/base.py", line 175, in render
    return self._render(context)
  File "/home/verghil/.local/lib/python3.10/site-packages/django/test/utils.py", line 112, in instrumented_test_render
    return self.nodelist.render(context)
  File "/home/verghil/.local/lib/python3.10/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/verghil/.local/lib/python3.10/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/verghil/.local/lib/python3.10/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/verghil/.local/lib/python3.10/site-packages/django/template/loader_tags.py", line 157, in render
    return compiled_parent._render(context)
  File "/home/verghil/.local/lib/python3.10/site-packages/django/test/utils.py", line 112, in instrumented_test_render
    return self.nodelist.render(context)
  File "/home/verghil/.local/lib/python3.10/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/verghil/.local/lib/python3.10/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/verghil/.local/lib/python3.10/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/verghil/.local/lib/python3.10/site-packages/django/template/loader_tags.py", line 63, in render
    result = block.nodelist.render(context)
  File "/home/verghil/.local/lib/python3.10/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/verghil/.local/lib/python3.10/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/verghil/.local/lib/python3.10/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/verghil/.local/lib/python3.10/site-packages/django/template/defaulttags.py", line 321, in render
    return nodelist.render(context)
  File "/home/verghil/.local/lib/python3.10/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/verghil/.local/lib/python3.10/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/verghil/.local/lib/python3.10/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/verghil/.local/lib/python3.10/site-packages/django/template/defaulttags.py", line 238, in render
    nodelist.append(node.render_annotated(context))
  File "/home/verghil/.local/lib/python3.10/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/verghil/.local/lib/python3.10/site-packages/django/template/defaulttags.py", line 471, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "/home/verghil/.local/lib/python3.10/site-packages/django/urls/base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "/home/verghil/.local/lib/python3.10/site-packages/django/urls/resolvers.py", line 828, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for '' not found. '' is not a valid view function or pattern name.
2023-10-08 19:34:35,903 [INFO] django.utils.autoreload: /home/verghil/Desktop/python_django/somesite/BlogApp/urls.py changed, reloading.
2023-10-08 19:34:42,700 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-10-08 19:34:49,471 [ERROR] django.request: Internal Server Error: /ru/article/articles/
Traceback (most recent call last):
  File "/home/verghil/.local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/verghil/.local/lib/python3.10/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
  File "/home/verghil/.local/lib/python3.10/site-packages/sentry_sdk/integrations/django/views.py", line 38, in sentry_patched_render
    return old_render(self)
  File "/home/verghil/.local/lib/python3.10/site-packages/django/template/response.py", line 114, in render
    self.content = self.rendered_content
  File "/home/verghil/.local/lib/python3.10/site-packages/sentry_sdk/integrations/django/templates.py", line 75, in rendered_content
    return real_rendered_content.fget(self)
  File "/home/verghil/.local/lib/python3.10/site-packages/django/template/response.py", line 92, in rendered_content
    return template.render(context, self._request)
  File "/home/verghil/.local/lib/python3.10/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/home/verghil/.local/lib/python3.10/site-packages/django/template/base.py", line 175, in render
    return self._render(context)
  File "/home/verghil/.local/lib/python3.10/site-packages/django/test/utils.py", line 112, in instrumented_test_render
    return self.nodelist.render(context)
  File "/home/verghil/.local/lib/python3.10/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/verghil/.local/lib/python3.10/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/verghil/.local/lib/python3.10/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/verghil/.local/lib/python3.10/site-packages/django/template/loader_tags.py", line 157, in render
    return compiled_parent._render(context)
  File "/home/verghil/.local/lib/python3.10/site-packages/django/test/utils.py", line 112, in instrumented_test_render
    return self.nodelist.render(context)
  File "/home/verghil/.local/lib/python3.10/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/verghil/.local/lib/python3.10/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/verghil/.local/lib/python3.10/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/verghil/.local/lib/python3.10/site-packages/django/template/loader_tags.py", line 63, in render
    result = block.nodelist.render(context)
  File "/home/verghil/.local/lib/python3.10/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/verghil/.local/lib/python3.10/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/verghil/.local/lib/python3.10/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/verghil/.local/lib/python3.10/site-packages/django/template/defaulttags.py", line 321, in render
    return nodelist.render(context)
  File "/home/verghil/.local/lib/python3.10/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/verghil/.local/lib/python3.10/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/verghil/.local/lib/python3.10/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/verghil/.local/lib/python3.10/site-packages/django/template/defaulttags.py", line 238, in render
    nodelist.append(node.render_annotated(context))
  File "/home/verghil/.local/lib/python3.10/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/verghil/.local/lib/python3.10/site-packages/django/template/defaulttags.py", line 471, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "/home/verghil/.local/lib/python3.10/site-packages/django/urls/base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "/home/verghil/.local/lib/python3.10/site-packages/django/urls/resolvers.py", line 828, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'articles' not found. 'articles' is not a valid view function or pattern name.
2023-10-08 19:35:35,861 [ERROR] django.request: Internal Server Error: /ru/article/articles/
Traceback (most recent call last):
  File "/home/verghil/.local/lib/python3.10/site-packages/django/urls/base.py", line 71, in reverse
    extra, resolver = resolver.namespace_dict[ns]
KeyError: 'BlogApp'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/verghil/.local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/verghil/.local/lib/python3.10/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
  File "/home/verghil/.local/lib/python3.10/site-packages/sentry_sdk/integrations/django/views.py", line 38, in sentry_patched_render
    return old_render(self)
  File "/home/verghil/.local/lib/python3.10/site-packages/django/template/response.py", line 114, in render
    self.content = self.rendered_content
  File "/home/verghil/.local/lib/python3.10/site-packages/sentry_sdk/integrations/django/templates.py", line 75, in rendered_content
    return real_rendered_content.fget(self)
  File "/home/verghil/.local/lib/python3.10/site-packages/django/template/response.py", line 92, in rendered_content
    return template.render(context, self._request)
  File "/home/verghil/.local/lib/python3.10/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/home/verghil/.local/lib/python3.10/site-packages/django/template/base.py", line 175, in render
    return self._render(context)
  File "/home/verghil/.local/lib/python3.10/site-packages/django/test/utils.py", line 112, in instrumented_test_render
    return self.nodelist.render(context)
  File "/home/verghil/.local/lib/python3.10/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/verghil/.local/lib/python3.10/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/verghil/.local/lib/python3.10/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/verghil/.local/lib/python3.10/site-packages/django/template/loader_tags.py", line 157, in render
    return compiled_parent._render(context)
  File "/home/verghil/.local/lib/python3.10/site-packages/django/test/utils.py", line 112, in instrumented_test_render
    return self.nodelist.render(context)
  File "/home/verghil/.local/lib/python3.10/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/verghil/.local/lib/python3.10/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/verghil/.local/lib/python3.10/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/verghil/.local/lib/python3.10/site-packages/django/template/loader_tags.py", line 63, in render
    result = block.nodelist.render(context)
  File "/home/verghil/.local/lib/python3.10/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/verghil/.local/lib/python3.10/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/verghil/.local/lib/python3.10/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/verghil/.local/lib/python3.10/site-packages/django/template/defaulttags.py", line 321, in render
    return nodelist.render(context)
  File "/home/verghil/.local/lib/python3.10/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/verghil/.local/lib/python3.10/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/verghil/.local/lib/python3.10/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/verghil/.local/lib/python3.10/site-packages/django/template/defaulttags.py", line 238, in render
    nodelist.append(node.render_annotated(context))
  File "/home/verghil/.local/lib/python3.10/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/verghil/.local/lib/python3.10/site-packages/django/template/defaulttags.py", line 471, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "/home/verghil/.local/lib/python3.10/site-packages/django/urls/base.py", line 82, in reverse
    raise NoReverseMatch("%s is not a registered namespace" % key)
django.urls.exceptions.NoReverseMatch: 'BlogApp' is not a registered namespace
2023-10-08 19:35:44,943 [ERROR] django.request: Internal Server Error: /ru/article/articles/
Traceback (most recent call last):
  File "/home/verghil/.local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/verghil/.local/lib/python3.10/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
  File "/home/verghil/.local/lib/python3.10/site-packages/sentry_sdk/integrations/django/views.py", line 38, in sentry_patched_render
    return old_render(self)
  File "/home/verghil/.local/lib/python3.10/site-packages/django/template/response.py", line 114, in render
    self.content = self.rendered_content
  File "/home/verghil/.local/lib/python3.10/site-packages/sentry_sdk/integrations/django/templates.py", line 75, in rendered_content
    return real_rendered_content.fget(self)
  File "/home/verghil/.local/lib/python3.10/site-packages/django/template/response.py", line 92, in rendered_content
    return template.render(context, self._request)
  File "/home/verghil/.local/lib/python3.10/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/home/verghil/.local/lib/python3.10/site-packages/django/template/base.py", line 175, in render
    return self._render(context)
  File "/home/verghil/.local/lib/python3.10/site-packages/django/test/utils.py", line 112, in instrumented_test_render
    return self.nodelist.render(context)
  File "/home/verghil/.local/lib/python3.10/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/verghil/.local/lib/python3.10/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/verghil/.local/lib/python3.10/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/verghil/.local/lib/python3.10/site-packages/django/template/loader_tags.py", line 157, in render
    return compiled_parent._render(context)
  File "/home/verghil/.local/lib/python3.10/site-packages/django/test/utils.py", line 112, in instrumented_test_render
    return self.nodelist.render(context)
  File "/home/verghil/.local/lib/python3.10/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/verghil/.local/lib/python3.10/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/verghil/.local/lib/python3.10/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/verghil/.local/lib/python3.10/site-packages/django/template/loader_tags.py", line 63, in render
    result = block.nodelist.render(context)
  File "/home/verghil/.local/lib/python3.10/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/verghil/.local/lib/python3.10/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/verghil/.local/lib/python3.10/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/verghil/.local/lib/python3.10/site-packages/django/template/defaulttags.py", line 321, in render
    return nodelist.render(context)
  File "/home/verghil/.local/lib/python3.10/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/verghil/.local/lib/python3.10/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/verghil/.local/lib/python3.10/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/verghil/.local/lib/python3.10/site-packages/django/template/defaulttags.py", line 238, in render
    nodelist.append(node.render_annotated(context))
  File "/home/verghil/.local/lib/python3.10/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/verghil/.local/lib/python3.10/site-packages/django/template/defaulttags.py", line 471, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "/home/verghil/.local/lib/python3.10/site-packages/django/urls/base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "/home/verghil/.local/lib/python3.10/site-packages/django/urls/resolvers.py", line 828, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'articles' not found. 'articles' is not a valid view function or pattern name.
2023-10-08 19:38:55,705 [INFO] django.utils.autoreload: /home/verghil/Desktop/python_django/somesite/BlogApp/urls.py changed, reloading.
2023-10-08 19:39:02,328 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-10-08 19:39:27,200 [ERROR] django.request: Internal Server Error: /ru/article/articles/
Traceback (most recent call last):
  File "/home/verghil/.local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/verghil/.local/lib/python3.10/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
  File "/home/verghil/.local/lib/python3.10/site-packages/sentry_sdk/integrations/django/views.py", line 38, in sentry_patched_render
    return old_render(self)
  File "/home/verghil/.local/lib/python3.10/site-packages/django/template/response.py", line 114, in render
    self.content = self.rendered_content
  File "/home/verghil/.local/lib/python3.10/site-packages/sentry_sdk/integrations/django/templates.py", line 75, in rendered_content
    return real_rendered_content.fget(self)
  File "/home/verghil/.local/lib/python3.10/site-packages/django/template/response.py", line 92, in rendered_content
    return template.render(context, self._request)
  File "/home/verghil/.local/lib/python3.10/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/home/verghil/.local/lib/python3.10/site-packages/django/template/base.py", line 175, in render
    return self._render(context)
  File "/home/verghil/.local/lib/python3.10/site-packages/django/test/utils.py", line 112, in instrumented_test_render
    return self.nodelist.render(context)
  File "/home/verghil/.local/lib/python3.10/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/verghil/.local/lib/python3.10/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/verghil/.local/lib/python3.10/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/verghil/.local/lib/python3.10/site-packages/django/template/loader_tags.py", line 157, in render
    return compiled_parent._render(context)
  File "/home/verghil/.local/lib/python3.10/site-packages/django/test/utils.py", line 112, in instrumented_test_render
    return self.nodelist.render(context)
  File "/home/verghil/.local/lib/python3.10/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/verghil/.local/lib/python3.10/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/verghil/.local/lib/python3.10/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/verghil/.local/lib/python3.10/site-packages/django/template/loader_tags.py", line 63, in render
    result = block.nodelist.render(context)
  File "/home/verghil/.local/lib/python3.10/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/verghil/.local/lib/python3.10/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/verghil/.local/lib/python3.10/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/verghil/.local/lib/python3.10/site-packages/django/template/defaulttags.py", line 321, in render
    return nodelist.render(context)
  File "/home/verghil/.local/lib/python3.10/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/verghil/.local/lib/python3.10/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/verghil/.local/lib/python3.10/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/verghil/.local/lib/python3.10/site-packages/django/template/defaulttags.py", line 238, in render
    nodelist.append(node.render_annotated(context))
  File "/home/verghil/.local/lib/python3.10/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/verghil/.local/lib/python3.10/site-packages/django/template/defaulttags.py", line 471, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "/home/verghil/.local/lib/python3.10/site-packages/django/urls/base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "/home/verghil/.local/lib/python3.10/site-packages/django/urls/resolvers.py", line 828, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'articles' not found. 'articles' is not a valid view function or pattern name.
2023-10-08 19:40:08,846 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-10-08 19:40:16,784 [ERROR] django.request: Internal Server Error: /ru/article/articles/
Traceback (most recent call last):
  File "/home/verghil/.local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/verghil/.local/lib/python3.10/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
  File "/home/verghil/.local/lib/python3.10/site-packages/sentry_sdk/integrations/django/views.py", line 38, in sentry_patched_render
    return old_render(self)
  File "/home/verghil/.local/lib/python3.10/site-packages/django/template/response.py", line 114, in render
    self.content = self.rendered_content
  File "/home/verghil/.local/lib/python3.10/site-packages/sentry_sdk/integrations/django/templates.py", line 75, in rendered_content
    return real_rendered_content.fget(self)
  File "/home/verghil/.local/lib/python3.10/site-packages/django/template/response.py", line 92, in rendered_content
    return template.render(context, self._request)
  File "/home/verghil/.local/lib/python3.10/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/home/verghil/.local/lib/python3.10/site-packages/django/template/base.py", line 175, in render
    return self._render(context)
  File "/home/verghil/.local/lib/python3.10/site-packages/django/test/utils.py", line 112, in instrumented_test_render
    return self.nodelist.render(context)
  File "/home/verghil/.local/lib/python3.10/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/verghil/.local/lib/python3.10/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/verghil/.local/lib/python3.10/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/verghil/.local/lib/python3.10/site-packages/django/template/loader_tags.py", line 157, in render
    return compiled_parent._render(context)
  File "/home/verghil/.local/lib/python3.10/site-packages/django/test/utils.py", line 112, in instrumented_test_render
    return self.nodelist.render(context)
  File "/home/verghil/.local/lib/python3.10/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/verghil/.local/lib/python3.10/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/verghil/.local/lib/python3.10/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/verghil/.local/lib/python3.10/site-packages/django/template/loader_tags.py", line 63, in render
    result = block.nodelist.render(context)
  File "/home/verghil/.local/lib/python3.10/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/verghil/.local/lib/python3.10/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/verghil/.local/lib/python3.10/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/verghil/.local/lib/python3.10/site-packages/django/template/defaulttags.py", line 321, in render
    return nodelist.render(context)
  File "/home/verghil/.local/lib/python3.10/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/verghil/.local/lib/python3.10/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/verghil/.local/lib/python3.10/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/verghil/.local/lib/python3.10/site-packages/django/template/defaulttags.py", line 238, in render
    nodelist.append(node.render_annotated(context))
  File "/home/verghil/.local/lib/python3.10/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/verghil/.local/lib/python3.10/site-packages/django/template/defaulttags.py", line 471, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "/home/verghil/.local/lib/python3.10/site-packages/django/urls/base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "/home/verghil/.local/lib/python3.10/site-packages/django/urls/resolvers.py", line 828, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'articles' with keyword arguments '{'pk': 1}' not found. 1 pattern(s) tried: ['ru/article/articles/\\Z']
2023-10-08 19:41:55,608 [WARNING] django.request: Not Found: /
2023-10-08 19:42:00,451 [WARNING] django.request: Not Found: /ru/
2023-10-08 19:42:04,358 [WARNING] django.request: Not Found: /ru/article/
2023-10-08 19:42:09,369 [ERROR] django.request: Internal Server Error: /ru/article/articles/
Traceback (most recent call last):
  File "/home/verghil/.local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/verghil/.local/lib/python3.10/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
  File "/home/verghil/.local/lib/python3.10/site-packages/sentry_sdk/integrations/django/views.py", line 38, in sentry_patched_render
    return old_render(self)
  File "/home/verghil/.local/lib/python3.10/site-packages/django/template/response.py", line 114, in render
    self.content = self.rendered_content
  File "/home/verghil/.local/lib/python3.10/site-packages/sentry_sdk/integrations/django/templates.py", line 75, in rendered_content
    return real_rendered_content.fget(self)
  File "/home/verghil/.local/lib/python3.10/site-packages/django/template/response.py", line 92, in rendered_content
    return template.render(context, self._request)
  File "/home/verghil/.local/lib/python3.10/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/home/verghil/.local/lib/python3.10/site-packages/django/template/base.py", line 175, in render
    return self._render(context)
  File "/home/verghil/.local/lib/python3.10/site-packages/django/test/utils.py", line 112, in instrumented_test_render
    return self.nodelist.render(context)
  File "/home/verghil/.local/lib/python3.10/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/verghil/.local/lib/python3.10/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/verghil/.local/lib/python3.10/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/verghil/.local/lib/python3.10/site-packages/django/template/loader_tags.py", line 157, in render
    return compiled_parent._render(context)
  File "/home/verghil/.local/lib/python3.10/site-packages/django/test/utils.py", line 112, in instrumented_test_render
    return self.nodelist.render(context)
  File "/home/verghil/.local/lib/python3.10/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/verghil/.local/lib/python3.10/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/verghil/.local/lib/python3.10/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/verghil/.local/lib/python3.10/site-packages/django/template/loader_tags.py", line 63, in render
    result = block.nodelist.render(context)
  File "/home/verghil/.local/lib/python3.10/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/verghil/.local/lib/python3.10/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/verghil/.local/lib/python3.10/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/verghil/.local/lib/python3.10/site-packages/django/template/defaulttags.py", line 321, in render
    return nodelist.render(context)
  File "/home/verghil/.local/lib/python3.10/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/verghil/.local/lib/python3.10/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/verghil/.local/lib/python3.10/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/verghil/.local/lib/python3.10/site-packages/django/template/defaulttags.py", line 238, in render
    nodelist.append(node.render_annotated(context))
  File "/home/verghil/.local/lib/python3.10/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/verghil/.local/lib/python3.10/site-packages/django/template/defaulttags.py", line 471, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "/home/verghil/.local/lib/python3.10/site-packages/django/urls/base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "/home/verghil/.local/lib/python3.10/site-packages/django/urls/resolvers.py", line 828, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'articles' with keyword arguments '{'pk': 1}' not found. 1 pattern(s) tried: ['ru/article/articles/\\Z']
2023-10-08 19:47:12,533 [INFO] django.utils.autoreload: /home/verghil/Desktop/python_django/somesite/BlogApp/admin.py changed, reloading.
2023-10-08 19:47:22,120 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-10-08 19:48:12,220 [INFO] django.utils.autoreload: /home/verghil/Desktop/python_django/somesite/BlogApp/admin.py changed, reloading.
2023-10-08 19:48:18,231 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-10-08 19:51:21,460 [INFO] django.utils.autoreload: /home/verghil/Desktop/python_django/somesite/BlogApp/admin.py changed, reloading.
2023-10-08 19:51:27,696 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-10-08 19:54:00,380 [INFO] django.utils.autoreload: /home/verghil/Desktop/python_django/somesite/BlogApp/admin.py changed, reloading.
2023-10-08 19:54:06,694 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-10-08 19:54:20,450 [INFO] django.utils.autoreload: /home/verghil/Desktop/python_django/somesite/BlogApp/admin.py changed, reloading.
2023-10-08 19:54:26,850 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-10-08 19:56:21,890 [INFO] django.utils.autoreload: /home/verghil/Desktop/python_django/somesite/BlogApp/admin.py changed, reloading.
2023-10-08 19:56:28,728 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-10-08 19:57:14,992 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-10-08 19:58:51,634 [WARNING] django.request: Not Found: /ru/article/
2023-10-08 19:58:57,075 [ERROR] django.request: Internal Server Error: /ru/article/articles/
Traceback (most recent call last):
  File "/home/verghil/.local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/verghil/.local/lib/python3.10/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
  File "/home/verghil/.local/lib/python3.10/site-packages/sentry_sdk/integrations/django/views.py", line 38, in sentry_patched_render
    return old_render(self)
  File "/home/verghil/.local/lib/python3.10/site-packages/django/template/response.py", line 114, in render
    self.content = self.rendered_content
  File "/home/verghil/.local/lib/python3.10/site-packages/sentry_sdk/integrations/django/templates.py", line 75, in rendered_content
    return real_rendered_content.fget(self)
  File "/home/verghil/.local/lib/python3.10/site-packages/django/template/response.py", line 92, in rendered_content
    return template.render(context, self._request)
  File "/home/verghil/.local/lib/python3.10/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/home/verghil/.local/lib/python3.10/site-packages/django/template/base.py", line 175, in render
    return self._render(context)
  File "/home/verghil/.local/lib/python3.10/site-packages/django/test/utils.py", line 112, in instrumented_test_render
    return self.nodelist.render(context)
  File "/home/verghil/.local/lib/python3.10/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/verghil/.local/lib/python3.10/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/verghil/.local/lib/python3.10/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/verghil/.local/lib/python3.10/site-packages/django/template/loader_tags.py", line 157, in render
    return compiled_parent._render(context)
  File "/home/verghil/.local/lib/python3.10/site-packages/django/test/utils.py", line 112, in instrumented_test_render
    return self.nodelist.render(context)
  File "/home/verghil/.local/lib/python3.10/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/verghil/.local/lib/python3.10/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/verghil/.local/lib/python3.10/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/verghil/.local/lib/python3.10/site-packages/django/template/loader_tags.py", line 63, in render
    result = block.nodelist.render(context)
  File "/home/verghil/.local/lib/python3.10/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/verghil/.local/lib/python3.10/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/verghil/.local/lib/python3.10/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/verghil/.local/lib/python3.10/site-packages/django/template/defaulttags.py", line 321, in render
    return nodelist.render(context)
  File "/home/verghil/.local/lib/python3.10/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/verghil/.local/lib/python3.10/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/verghil/.local/lib/python3.10/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/verghil/.local/lib/python3.10/site-packages/django/template/defaulttags.py", line 238, in render
    nodelist.append(node.render_annotated(context))
  File "/home/verghil/.local/lib/python3.10/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/verghil/.local/lib/python3.10/site-packages/django/template/defaulttags.py", line 471, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "/home/verghil/.local/lib/python3.10/site-packages/django/urls/base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "/home/verghil/.local/lib/python3.10/site-packages/django/urls/resolvers.py", line 828, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'articles' with keyword arguments '{'pk': 2}' not found. 1 pattern(s) tried: ['ru/article/articles/\\Z']
2023-10-08 20:03:36,266 [ERROR] django.request: Internal Server Error: /ru/article/articles/
Traceback (most recent call last):
  File "/home/verghil/.local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/verghil/.local/lib/python3.10/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
  File "/home/verghil/.local/lib/python3.10/site-packages/sentry_sdk/integrations/django/views.py", line 38, in sentry_patched_render
    return old_render(self)
  File "/home/verghil/.local/lib/python3.10/site-packages/django/template/response.py", line 114, in render
    self.content = self.rendered_content
  File "/home/verghil/.local/lib/python3.10/site-packages/sentry_sdk/integrations/django/templates.py", line 75, in rendered_content
    return real_rendered_content.fget(self)
  File "/home/verghil/.local/lib/python3.10/site-packages/django/template/response.py", line 92, in rendered_content
    return template.render(context, self._request)
  File "/home/verghil/.local/lib/python3.10/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/home/verghil/.local/lib/python3.10/site-packages/django/template/base.py", line 175, in render
    return self._render(context)
  File "/home/verghil/.local/lib/python3.10/site-packages/django/test/utils.py", line 112, in instrumented_test_render
    return self.nodelist.render(context)
  File "/home/verghil/.local/lib/python3.10/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/verghil/.local/lib/python3.10/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/verghil/.local/lib/python3.10/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/verghil/.local/lib/python3.10/site-packages/django/template/loader_tags.py", line 157, in render
    return compiled_parent._render(context)
  File "/home/verghil/.local/lib/python3.10/site-packages/django/test/utils.py", line 112, in instrumented_test_render
    return self.nodelist.render(context)
  File "/home/verghil/.local/lib/python3.10/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/verghil/.local/lib/python3.10/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/verghil/.local/lib/python3.10/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/verghil/.local/lib/python3.10/site-packages/django/template/loader_tags.py", line 63, in render
    result = block.nodelist.render(context)
  File "/home/verghil/.local/lib/python3.10/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/verghil/.local/lib/python3.10/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/verghil/.local/lib/python3.10/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/verghil/.local/lib/python3.10/site-packages/django/template/defaulttags.py", line 321, in render
    return nodelist.render(context)
  File "/home/verghil/.local/lib/python3.10/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/verghil/.local/lib/python3.10/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/verghil/.local/lib/python3.10/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/verghil/.local/lib/python3.10/site-packages/django/template/defaulttags.py", line 238, in render
    nodelist.append(node.render_annotated(context))
  File "/home/verghil/.local/lib/python3.10/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/verghil/.local/lib/python3.10/site-packages/django/template/defaulttags.py", line 471, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "/home/verghil/.local/lib/python3.10/site-packages/django/urls/base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "/home/verghil/.local/lib/python3.10/site-packages/django/urls/resolvers.py", line 828, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'articles' with keyword arguments '{'pk': 2}' not found. 1 pattern(s) tried: ['ru/article/articles/\\Z']
2023-10-08 20:05:36,413 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-10-08 20:08:54,021 [INFO] django.utils.autoreload: /home/verghil/Desktop/python_django/somesite/BlogApp/urls.py changed, reloading.
2023-10-08 20:09:00,855 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-10-08 20:09:03,948 [WARNING] django.request: Not Found: /ru/article/articles/2/
2023-10-08 20:09:17,053 [INFO] django.utils.autoreload: /home/verghil/Desktop/python_django/somesite/BlogApp/urls.py changed, reloading.
2023-10-08 20:09:23,699 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-10-08 20:09:25,870 [WARNING] django.request: Not Found: /ru/article/articles/2/
2023-10-08 20:09:57,640 [INFO] django.utils.autoreload: /home/verghil/Desktop/python_django/somesite/BlogApp/urls.py changed, reloading.
2023-10-08 20:10:04,909 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-10-08 20:10:36,561 [INFO] django.utils.autoreload: /home/verghil/Desktop/python_django/somesite/BlogApp/urls.py changed, reloading.
2023-10-08 20:10:45,575 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-10-08 20:11:12,095 [WARNING] django.request: Not Found: /ru/article/article/2/
2023-10-08 20:12:17,013 [INFO] django.utils.autoreload: /home/verghil/Desktop/python_django/somesite/BlogApp/views.py changed, reloading.
2023-10-08 20:12:24,406 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-10-08 20:12:26,743 [WARNING] django.request: Not Found: /ru/article/article/2/
2023-10-08 20:12:36,558 [ERROR] django.request: Internal Server Error: /ru/article/articles/2/
Traceback (most recent call last):
  File "/home/verghil/.local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/verghil/.local/lib/python3.10/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
  File "/home/verghil/.local/lib/python3.10/site-packages/sentry_sdk/integrations/django/views.py", line 38, in sentry_patched_render
    return old_render(self)
  File "/home/verghil/.local/lib/python3.10/site-packages/django/template/response.py", line 114, in render
    self.content = self.rendered_content
  File "/home/verghil/.local/lib/python3.10/site-packages/sentry_sdk/integrations/django/templates.py", line 75, in rendered_content
    return real_rendered_content.fget(self)
  File "/home/verghil/.local/lib/python3.10/site-packages/django/template/response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
  File "/home/verghil/.local/lib/python3.10/site-packages/django/template/response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
  File "/home/verghil/.local/lib/python3.10/site-packages/django/template/loader.py", line 47, in select_template
    raise TemplateDoesNotExist(", ".join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: BlogApp/article_detail.html
2023-10-08 20:13:24,067 [ERROR] django.request: Internal Server Error: /ru/article/articles/2/
Traceback (most recent call last):
  File "/home/verghil/.local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/verghil/.local/lib/python3.10/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
  File "/home/verghil/.local/lib/python3.10/site-packages/sentry_sdk/integrations/django/views.py", line 38, in sentry_patched_render
    return old_render(self)
  File "/home/verghil/.local/lib/python3.10/site-packages/django/template/response.py", line 114, in render
    self.content = self.rendered_content
  File "/home/verghil/.local/lib/python3.10/site-packages/sentry_sdk/integrations/django/templates.py", line 75, in rendered_content
    return real_rendered_content.fget(self)
  File "/home/verghil/.local/lib/python3.10/site-packages/django/template/response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
  File "/home/verghil/.local/lib/python3.10/site-packages/django/template/response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
  File "/home/verghil/.local/lib/python3.10/site-packages/django/template/loader.py", line 47, in select_template
    raise TemplateDoesNotExist(", ".join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: BlogApp/article_detail.html
2023-10-08 20:14:46,362 [INFO] django.utils.autoreload: /home/verghil/Desktop/python_django/somesite/BlogApp/views.py changed, reloading.
2023-10-08 20:14:53,448 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-10-08 20:14:57,914 [ERROR] django.request: Internal Server Error: /ru/article/articles/2/
Traceback (most recent call last):
  File "/home/verghil/.local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/verghil/.local/lib/python3.10/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
  File "/home/verghil/.local/lib/python3.10/site-packages/sentry_sdk/integrations/django/views.py", line 38, in sentry_patched_render
    return old_render(self)
  File "/home/verghil/.local/lib/python3.10/site-packages/django/template/response.py", line 114, in render
    self.content = self.rendered_content
  File "/home/verghil/.local/lib/python3.10/site-packages/sentry_sdk/integrations/django/templates.py", line 75, in rendered_content
    return real_rendered_content.fget(self)
  File "/home/verghil/.local/lib/python3.10/site-packages/django/template/response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
  File "/home/verghil/.local/lib/python3.10/site-packages/django/template/response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
  File "/home/verghil/.local/lib/python3.10/site-packages/django/template/loader.py", line 42, in select_template
    return engine.get_template(template_name)
  File "/home/verghil/.local/lib/python3.10/site-packages/django/template/backends/django.py", line 33, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "/home/verghil/.local/lib/python3.10/site-packages/django/template/engine.py", line 175, in get_template
    template, origin = self.find_template(template_name)
  File "/home/verghil/.local/lib/python3.10/site-packages/django/template/engine.py", line 157, in find_template
    template = loader.get_template(name, skip=skip)
  File "/home/verghil/.local/lib/python3.10/site-packages/django/template/loaders/cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
  File "/home/verghil/.local/lib/python3.10/site-packages/django/template/loaders/base.py", line 28, in get_template
    return Template(
  File "/home/verghil/.local/lib/python3.10/site-packages/django/template/base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
  File "/home/verghil/.local/lib/python3.10/site-packages/django/template/base.py", line 200, in compile_nodelist
    return parser.parse()
  File "/home/verghil/.local/lib/python3.10/site-packages/django/template/base.py", line 513, in parse
    raise self.error(token, e)
  File "/home/verghil/.local/lib/python3.10/site-packages/django/template/base.py", line 511, in parse
    compiled_result = compile_func(self, token)
  File "/home/verghil/.local/lib/python3.10/site-packages/django/template/loader_tags.py", line 292, in do_extends
    parent_name = parser.compile_filter(bits[1])
  File "/home/verghil/.local/lib/python3.10/site-packages/django/template/base.py", line 600, in compile_filter
    return FilterExpression(token, self)
  File "/home/verghil/.local/lib/python3.10/site-packages/django/template/base.py", line 703, in __init__
    raise TemplateSyntaxError(
django.template.exceptions.TemplateSyntaxError: Could not parse the remainder: ''blogapp/base.html' from ''blogapp/base.html'
2023-10-08 20:17:50,241 [INFO] django.utils.autoreload: /home/verghil/Desktop/python_django/somesite/BlogApp/views.py changed, reloading.
2023-10-08 20:18:03,207 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-10-08 20:18:10,907 [INFO] django.utils.autoreload: /home/verghil/Desktop/python_django/somesite/BlogApp/views.py changed, reloading.
2023-10-08 20:18:21,002 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-10-08 20:21:31,032 [INFO] django.utils.autoreload: /home/verghil/Desktop/python_django/somesite/BlogApp/views.py changed, reloading.
2023-10-08 20:21:44,480 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-10-08 20:21:52,947 [INFO] django.utils.autoreload: /home/verghil/Desktop/python_django/somesite/BlogApp/views.py changed, reloading.
2023-10-08 20:22:02,279 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-10-08 20:22:22,483 [INFO] django.utils.autoreload: /home/verghil/Desktop/python_django/somesite/BlogApp/views.py changed, reloading.
2023-10-08 20:22:29,000 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-10-08 20:22:33,803 [INFO] django.utils.autoreload: /home/verghil/Desktop/python_django/somesite/BlogApp/views.py changed, reloading.
2023-10-08 20:22:47,457 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-10-08 20:23:16,490 [INFO] django.utils.autoreload: /home/verghil/Desktop/python_django/somesite/BlogApp/views.py changed, reloading.
2023-10-08 20:23:32,012 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-10-08 20:24:01,112 [INFO] django.utils.autoreload: /home/verghil/Desktop/python_django/somesite/BlogApp/views.py changed, reloading.
2023-10-08 20:24:11,317 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-10-08 20:25:29,908 [INFO] django.utils.autoreload: /home/verghil/Desktop/python_django/somesite/BlogApp/urls.py changed, reloading.
2023-10-08 20:25:36,788 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-10-08 20:25:42,061 [INFO] django.utils.autoreload: /home/verghil/Desktop/python_django/somesite/BlogApp/urls.py changed, reloading.
2023-10-08 20:25:52,536 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-10-08 20:29:51,713 [INFO] django.utils.autoreload: /home/verghil/Desktop/python_django/somesite/somesite/urls.py changed, reloading.
2023-10-08 20:29:58,221 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-10-08 20:34:07,747 [WARNING] django.request: Not Found: /favicon.ico
2023-10-08 20:41:26,624 [INFO] django.utils.autoreload: /home/verghil/Desktop/python_django/somesite/BlogApp/models.py changed, reloading.
2023-10-08 20:41:37,995 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-10-08 20:41:48,266 [INFO] django.utils.autoreload: /home/verghil/Desktop/python_django/somesite/BlogApp/views.py changed, reloading.
2023-10-08 20:42:01,634 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-10-08 20:43:44,963 [INFO] django.utils.autoreload: /home/verghil/Desktop/python_django/somesite/somesite/urls.py changed, reloading.
2023-10-08 20:43:56,441 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-10-08 20:45:12,798 [INFO] django.utils.autoreload: /home/verghil/Desktop/python_django/somesite/somesite/urls.py changed, reloading.
2023-10-08 20:45:19,345 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-10-08 20:45:57,878 [INFO] django.utils.autoreload: /home/verghil/Desktop/python_django/somesite/somesite/urls.py changed, reloading.
2023-10-08 20:46:04,962 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-10-08 20:46:35,951 [INFO] django.utils.autoreload: /home/verghil/Desktop/python_django/somesite/somesite/urls.py changed, reloading.
2023-10-08 20:46:44,570 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-10-08 20:47:30,516 [INFO] django.utils.autoreload: /home/verghil/Desktop/python_django/somesite/somesite/settings.py changed, reloading.
2023-10-08 20:47:36,492 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-10-08 20:48:06,260 [ERROR] django.request: Internal Server Error: /ru/sitemap.xml
Traceback (most recent call last):
  File "/home/verghil/.local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/verghil/.local/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/verghil/.local/lib/python3.10/site-packages/sentry_sdk/integrations/django/views.py", line 84, in sentry_wrapped_callback
    return callback(request, *args, **kwargs)
  File "/home/verghil/.local/lib/python3.10/site-packages/django/contrib/sitemaps/views.py", line 34, in inner
    response = func(request, *args, **kwargs)
TypeError: sitemap() got an unexpected keyword argument 'sitemap'
2023-10-08 20:49:33,230 [INFO] django.utils.autoreload: /home/verghil/Desktop/python_django/somesite/somesite/urls.py changed, reloading.
2023-10-08 20:49:40,552 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-10-08 20:49:45,016 [ERROR] django.request: Internal Server Error: /ru/sitemap.xml
Traceback (most recent call last):
  File "/home/verghil/.local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/verghil/.local/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/verghil/.local/lib/python3.10/site-packages/sentry_sdk/integrations/django/views.py", line 84, in sentry_wrapped_callback
    return callback(request, *args, **kwargs)
  File "/home/verghil/.local/lib/python3.10/site-packages/django/contrib/sitemaps/views.py", line 34, in inner
    response = func(request, *args, **kwargs)
  File "/home/verghil/.local/lib/python3.10/site-packages/django/contrib/sitemaps/views.py", line 128, in sitemap
    urls.extend(site.get_urls(page=page, site=req_site, protocol=req_protocol))
AttributeError: 'BlogSitemap' object has no attribute 'get_urls'
2023-10-08 20:50:05,836 [INFO] django.utils.autoreload: /home/verghil/Desktop/python_django/somesite/somesite/urls.py changed, reloading.
2023-10-08 20:50:12,785 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-10-08 20:50:18,030 [ERROR] django.request: Internal Server Error: /sitemap.xml
Traceback (most recent call last):
  File "/home/verghil/.local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/verghil/.local/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/verghil/.local/lib/python3.10/site-packages/sentry_sdk/integrations/django/views.py", line 84, in sentry_wrapped_callback
    return callback(request, *args, **kwargs)
  File "/home/verghil/.local/lib/python3.10/site-packages/django/contrib/sitemaps/views.py", line 34, in inner
    response = func(request, *args, **kwargs)
  File "/home/verghil/.local/lib/python3.10/site-packages/django/contrib/sitemaps/views.py", line 128, in sitemap
    urls.extend(site.get_urls(page=page, site=req_site, protocol=req_protocol))
AttributeError: 'BlogSitemap' object has no attribute 'get_urls'
2023-10-08 20:51:16,619 [INFO] django.utils.autoreload: /home/verghil/Desktop/python_django/somesite/somesite/urls.py changed, reloading.
2023-10-08 20:51:28,179 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-10-08 20:54:06,035 [INFO] django.utils.autoreload: /home/verghil/Desktop/python_django/somesite/BlogApp/models.py changed, reloading.
2023-10-08 20:54:16,874 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-10-08 20:54:22,556 [ERROR] django.request: Internal Server Error: /sitemap.xml
Traceback (most recent call last):
  File "/home/verghil/.local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/verghil/.local/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/verghil/.local/lib/python3.10/site-packages/sentry_sdk/integrations/django/views.py", line 84, in sentry_wrapped_callback
    return callback(request, *args, **kwargs)
  File "/home/verghil/.local/lib/python3.10/site-packages/django/contrib/sitemaps/views.py", line 34, in inner
    response = func(request, *args, **kwargs)
  File "/home/verghil/.local/lib/python3.10/site-packages/django/contrib/sitemaps/views.py", line 128, in sitemap
    urls.extend(site.get_urls(page=page, site=req_site, protocol=req_protocol))
AttributeError: 'BlogSitemap' object has no attribute 'get_urls'
2023-10-08 20:55:12,633 [INFO] django.utils.autoreload: /home/verghil/Desktop/python_django/somesite/BlogApp/views.py changed, reloading.
2023-10-08 20:55:22,100 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-10-08 20:57:37,265 [INFO] django.utils.autoreload: /home/verghil/Desktop/python_django/somesite/BlogApp/views.py changed, reloading.
2023-10-08 20:57:45,408 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-10-08 20:58:34,642 [INFO] django.utils.autoreload: /home/verghil/Desktop/python_django/somesite/BlogApp/sitemap.py changed, reloading.
2023-10-08 20:58:41,388 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-10-08 20:58:45,750 [ERROR] django.request: Internal Server Error: /sitemap.xml
Traceback (most recent call last):
  File "/home/verghil/.local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/verghil/.local/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/verghil/.local/lib/python3.10/site-packages/sentry_sdk/integrations/django/views.py", line 84, in sentry_wrapped_callback
    return callback(request, *args, **kwargs)
  File "/home/verghil/.local/lib/python3.10/site-packages/django/contrib/sitemaps/views.py", line 34, in inner
    response = func(request, *args, **kwargs)
  File "/home/verghil/.local/lib/python3.10/site-packages/django/contrib/sitemaps/views.py", line 128, in sitemap
    urls.extend(site.get_urls(page=page, site=req_site, protocol=req_protocol))
AttributeError: 'BlogSitemap' object has no attribute 'get_urls'
2023-10-08 20:58:53,767 [INFO] django.utils.autoreload: /home/verghil/Desktop/python_django/somesite/BlogApp/sitemap.py changed, reloading.
2023-10-08 20:59:01,682 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-10-08 21:01:33,646 [INFO] django.utils.autoreload: /home/verghil/Desktop/python_django/somesite/BlogApp/sitemap.py changed, reloading.
2023-10-08 21:01:41,059 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-10-08 21:02:08,302 [INFO] django.utils.autoreload: /home/verghil/Desktop/python_django/somesite/BlogApp/sitemap.py changed, reloading.
2023-10-08 21:02:15,486 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-10-08 21:03:49,861 [INFO] django.utils.autoreload: /home/verghil/Desktop/python_django/somesite/somesite/urls.py changed, reloading.
2023-10-08 21:03:56,169 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-10-08 21:04:00,251 [INFO] django.utils.autoreload: /home/verghil/Desktop/python_django/somesite/somesite/urls.py changed, reloading.
2023-10-08 21:04:07,113 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-10-08 21:04:58,253 [INFO] django.utils.autoreload: /home/verghil/Desktop/python_django/somesite/BlogApp/sitemap.py changed, reloading.
2023-10-08 21:05:05,204 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-10-08 21:05:23,363 [INFO] django.utils.autoreload: /home/verghil/Desktop/python_django/somesite/BlogApp/sitemap.py changed, reloading.
2023-10-08 21:05:29,524 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-10-08 21:07:30,330 [INFO] django.utils.autoreload: /home/verghil/Desktop/python_django/somesite/BlogApp/sitemap.py changed, reloading.
2023-10-08 21:07:36,527 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-10-08 21:07:59,540 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-10-08 21:08:53,004 [INFO] django.utils.autoreload: /home/verghil/Desktop/python_django/somesite/BlogApp/views.py changed, reloading.
2023-10-08 21:08:59,796 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-10-10 16:42:47,004 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-10-10 16:42:51,218 [WARNING] django.request: Not Found: /
2023-10-10 16:43:37,893 [INFO] django.utils.autoreload: /home/verghil/Desktop/python_django/somesite/somesite/sitemaps.py changed, reloading.
2023-10-10 16:43:44,626 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-10-10 16:44:15,699 [INFO] shopapp.views: Rendering shop index
2023-10-10 16:44:27,435 [WARNING] django.request: Not Found: /ru/shop/latest/feed
2023-10-10 16:45:34,079 [WARNING] django.request: Not Found: /
2023-10-10 16:45:38,861 [WARNING] django.request: Not Found: /ru/
2023-10-10 16:46:02,466 [INFO] shopapp.views: Rendering shop index
2023-10-10 16:46:14,285 [WARNING] django.request: Not Found: /ru/shop/products/latest
2023-10-10 16:47:07,153 [WARNING] django.request: Not Found: /ru/shop/products/latest
2023-10-10 16:47:17,054 [WARNING] django.request: Not Found: /ru/shop/products/latest/feed/2звонилка
2023-10-10 16:47:20,386 [WARNING] django.request: Not Found: /ru/shop/products/latest/feed/2звонилка.
2023-10-10 16:47:23,469 [WARNING] django.request: Not Found: /ru/shop/products/latest/feed/2звонилка/
2023-10-10 16:47:28,695 [WARNING] django.request: Not Found: /ru/shop/products/latest/feed/2/
2023-10-10 16:48:08,763 [WARNING] django.request: Not Found: /ru/blog/articles/latest/
2023-10-10 16:48:19,403 [ERROR] django.request: Internal Server Error: /ru/blog/articles/latest/feed/
Traceback (most recent call last):
  File "/home/verghil/.local/lib/python3.10/site-packages/django/contrib/syndication/views.py", line 60, in item_link
    return item.get_absolute_url()
AttributeError: 'Article' object has no attribute 'get_absolute_url'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/verghil/.local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/verghil/.local/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/verghil/.local/lib/python3.10/site-packages/sentry_sdk/integrations/django/views.py", line 84, in sentry_wrapped_callback
    return callback(request, *args, **kwargs)
  File "/home/verghil/.local/lib/python3.10/site-packages/django/contrib/syndication/views.py", line 40, in __call__
    feedgen = self.get_feed(obj, request)
  File "/home/verghil/.local/lib/python3.10/site-packages/django/contrib/syndication/views.py", line 194, in get_feed
    self._get_dynamic_attr("item_link", item),
  File "/home/verghil/.local/lib/python3.10/site-packages/django/contrib/syndication/views.py", line 103, in _get_dynamic_attr
    return attr(obj)
  File "/home/verghil/.local/lib/python3.10/site-packages/django/contrib/syndication/views.py", line 62, in item_link
    raise ImproperlyConfigured(
django.core.exceptions.ImproperlyConfigured: Give your Article class a get_absolute_url() method, or define an item_link() method in your Feed class.
2023-10-10 16:48:28,184 [WARNING] django.request: Not Found: /ru/blog/articles/latest/feed/1
2023-10-10 16:48:31,265 [WARNING] django.request: Not Found: /ru/blog/articles/latest/feed/2
2023-10-10 16:48:58,634 [WARNING] django.request: Not Found: /ru/shop/products/latest
2023-10-10 16:49:02,625 [ERROR] django.request: Internal Server Error: /ru/shop/products/latest/feed/
Traceback (most recent call last):
  File "/home/verghil/.local/lib/python3.10/site-packages/django/contrib/syndication/views.py", line 60, in item_link
    return item.get_absolute_url()
AttributeError: 'Product' object has no attribute 'get_absolute_url'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/verghil/.local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/verghil/.local/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/verghil/.local/lib/python3.10/site-packages/sentry_sdk/integrations/django/views.py", line 84, in sentry_wrapped_callback
    return callback(request, *args, **kwargs)
  File "/home/verghil/.local/lib/python3.10/site-packages/django/contrib/syndication/views.py", line 40, in __call__
    feedgen = self.get_feed(obj, request)
  File "/home/verghil/.local/lib/python3.10/site-packages/django/contrib/syndication/views.py", line 194, in get_feed
    self._get_dynamic_attr("item_link", item),
  File "/home/verghil/.local/lib/python3.10/site-packages/django/contrib/syndication/views.py", line 103, in _get_dynamic_attr
    return attr(obj)
  File "/home/verghil/.local/lib/python3.10/site-packages/django/contrib/syndication/views.py", line 62, in item_link
    raise ImproperlyConfigured(
django.core.exceptions.ImproperlyConfigured: Give your Product class a get_absolute_url() method, or define an item_link() method in your Feed class.
2023-10-10 16:49:03,353 [WARNING] django.request: Not Found: /favicon.ico
